"""Generic sample configuration generated by this tool."""

from __future__ import annotations

from ha_streamdeck_gui.schema import Button, Dial, Page, StreamDeckConfig
from ha_streamdeck_gui.yaml_io import dump_config_yaml


def build_sample_config() -> StreamDeckConfig:
    """Multi-page Stream Deck + example with no site-specific identifiers."""
    home = Page(
        name="Home",
        buttons=[
            Button(
                entity_id="light.kitchen",
                service="light.toggle",
                text="Kitchen",
                icon_mdi="lightbulb",
                icon_mdi_color="#FFC107",
            ),
            Button(
                entity_id="light.living_room",
                special_type="light-control",
                special_type_data={"colormap": "hsv"},
                text="Living\nroom",
                icon_mdi="lamp",
                long_press={"service": "light.toggle"},
            ),
            Button(
                special_type="go-to-page",
                special_type_data="Media",
                text="Media",
                icon_mdi="play-circle",
            ),
            Button(
                special_type="go-to-page",
                special_type_data="Scenes",
                text="Scenes",
                icon_mdi="palette",
            ),
            Button(
                special_type="go-to-page",
                special_type_data="all-lights",
                text="All\nlights",
                icon_mdi="lightbulb-group",
            ),
            Button(
                special_type="turn-off",
                text="Sleep\ndeck",
                icon_mdi="power-sleep",
            ),
            Button(special_type="previous-page", icon_mdi="chevron-left", text="Prev"),
            Button(special_type="next-page", icon_mdi="chevron-right", text="Next"),
        ],
        dials=[
            Dial(
                entity_id="light.kitchen",
                service="light.turn_on",
                service_data={"brightness": "{{ dial_value() | int }}"},
                dial_event_type="TURN",
                state_attribute="brightness",
                delay=0.5,
                allow_touchscreen_events=True,
                attributes={"min": 0, "max": 255, "step": 5},
                text="{{ dial_value() | int }}",
                icon="ring:{{ ((dial_value() / 255) * 100) | round }}",
                icon_mdi="brightness-6",
            ),
            Dial(
                entity_id="light.kitchen",
                service="light.toggle",
                dial_event_type="PUSH",
                text="Kitchen",
                icon_mdi="lightbulb",
            ),
            Dial(
                entity_id="media_player.living_room",
                service="media_player.volume_set",
                service_data={"volume_level": "{{ dial_value() }}"},
                dial_event_type="TURN",
                state_attribute="volume_level",
                attributes={"min": 0, "max": 1, "step": 0.05},
                text="Vol",
                icon_mdi="volume-high",
            ),
            Dial(
                entity_id="media_player.living_room",
                service="media_player.media_play_pause",
                dial_event_type="PUSH",
                icon_mdi="play-pause",
            ),
            Dial(
                entity_id="climate.living_room",
                service="climate.set_temperature",
                service_data={"temperature": "{{ dial_value() }}"},
                dial_event_type="TURN",
                state_attribute="temperature",
                attributes={"min": 16, "max": 26, "step": 0.5},
                text="{{ dial_value() }}°",
                icon_mdi="thermostat",
            ),
            Dial(
                entity_id="input_number.example",
                service="input_number.set_value",
                service_data={"value": "{{ dial_value() }}"},
                dial_event_type="TURN",
                attributes={"min": 0, "max": 100, "step": 1},
                text="{{ dial_value() | int }}",
                icon="ring:{{ dial_value() | int }}",
            ),
        ],
    )
    media = Page(
        name="Media",
        buttons=[
            Button(
                entity_id="media_player.living_room",
                service="media_player.media_play_pause",
                text="Play",
                icon_mdi="play-pause",
            ),
            Button(
                entity_id="media_player.living_room",
                service="media_player.volume_mute",
                text="Mute",
                icon_mdi="volume-off",
            ),
            Button(special_type="empty"),
            Button(
                special_type="go-to-page",
                special_type_data="Home",
                text="Home",
                icon_mdi="home",
            ),
        ],
    )
    scenes = Page(
        name="Scenes",
        buttons=[
            Button(
                entity_id="scene.movie_night",
                service="scene.turn_on",
                text="Movie\nnight",
                icon_mdi="movie",
            ),
            Button(
                entity_id="scene.good_morning",
                service="scene.turn_on",
                text="Morning",
                icon_mdi="weather-sunset-up",
            ),
            Button(special_type="close-page", text="Back", icon_mdi="keyboard-return"),
            Button(special_type="reload", text="Reload", icon_mdi="refresh"),
        ],
    )
    all_lights = Page(
        name="all-lights",
        buttons=[
            Button(entity_id="light.kitchen", service="light.toggle", text="Kitchen"),
            Button(entity_id="light.living_room", service="light.toggle", text="Living"),
            Button(entity_id="light.bedroom", service="light.toggle", text="Bedroom"),
            Button(special_type="empty"),
            Button(special_type="empty"),
            Button(special_type="empty"),
            Button(special_type="empty"),
            Button(special_type="close-page", text="Back", icon_mdi="keyboard-return"),
        ],
    )
    return StreamDeckConfig(
        brightness=80,
        auto_reload=True,
        state_entity_id="input_boolean.streamdeck",
        long_press_duration=0.5,
        inactivity_time=300,
        pages=[home, media, scenes],
        anonymous_pages=[all_lights],
    )


def sample_yaml() -> str:
    return dump_config_yaml(build_sample_config())
